name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: setup.py
    - name: Cache models
      uses: actions/cache@v3
      with:
        path: ~/.cache
        key: ${{ runner.os }}-torch-
    - name: Install dependencies
      run: |
        pip install -e .
        pip install pytest
    - name: Run tests
      run: |
        python -m pytest -s

